20 feature 0 4 writing out the entities and interfaces global studyuser pools
CSC207-2022F-UofT/course-project-group-122 pull request #21
Opened 2022-11-02 18:14 UTC by j-y26

Completed the first version of the implementation.

2022-11-03 02:12 UTC, xuyangan submitted a review, later dismissed

2022-11-03 23:15 UTC, chelkisea requested changes
please review 2 small suggestions

2022-11-03 23:15 UTC, chelkisea commented on src/main/entities/StudyPool.java
> +     * @return the type of the study.
```suggestion
     * @return the type of the study if the given study ID exists, null otherwise
```

2022-11-03 23:15 UTC, chelkisea commented on src/main/entities/UserPool.java
> +     * @return the type of user.
```suggestion
     * @return the type of user if the given username exists, null otherwise.
```

2022-11-04 06:55 UTC, chelkisea approved these changes

2022-11-05 03:29 UTC, xuyangan approved these changes

2022-11-05 15:00 UTC, Jerryfish0807 approved these changes
wonderful!!!

2022-11-05 15:17 UTC, merged