11 feature 11 result pulling and extraction
CSC207-2022F-UofT/course-project-group-122 pull request #60
Opened 2022-11-27 17:10 UTC by Jerryfish0807

Fully establish the feature of exporting but lacks peer-reviewed. (Java Doc has been entirely written, please use it as a reference to test)

2022-11-27 21:03 UTC, j-y26 requested changes
This is in general a very good use case that satisfies the specification. However, please do refactor many parts I commented into helper methods. In addition, this use case should use a Builder Design pattern.  Thus, for the methods mentioned previously about refactoring, refactor them into another class called StudyResulltBuilder and define the aforementioned methods. Inject this builder class into the interactor class so that your interactor uses these methods in the same process where you are creating the csv files now.

2022-11-28 01:07 UTC, Tedward765 approved these changes
:)

2022-11-29 21:43 UTC, j-y26 approved these changes
This version of the result extraction use case has made significant improvements compared to the previous version by incorporating the use of a Builder design pattern. The interaction now does not contain any code smells with a step-by-step process to call the builder to build the "saved results". 

One small thing that can be improved is to use dependency injection to inject the builder into the interactor, without directly initializing the builder with the new method. However, this is minor and the use case is good enough to be merged to main.

2022-11-29 21:43 UTC, j-y26 commented on src/main/java/use_cases/result_extraction/ResultExtractionInteractor.java
> +        ResultExtractionBuilder fBuilder = new ResultExtractionBuilder();
The hard dependency here can be made to dependency injection

2022-12-02 20:30 UTC, j-y26 submitted a review, later dismissed

2022-12-02 22:17 UTC, Tedward765 approved these changes
:)

2022-12-02 23:04 UTC, xuyangan submitted a review, later dismissed
Nice job on using the builder pattern instead of a switch block.

2022-12-02 23:07 UTC, xuyangan approved these changes
I deleted the conflicts so that the branch can be merged to main.

2022-12-02 23:08 UTC, j-y26 approved these changes
Conflict resolved. Conflict resolved

2022-12-02 23:09 UTC, xustell approved these changes
okay!

2022-12-02 23:09 UTC, merged